services:
  postgres:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    ports:
      - 5433:5432
    labels:
      org.springframework.boot.service-connection: postgres


volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.mnt/postgres/data


networks:
  cipher:
