apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cipher-quest-be
  namespace: welld-staging
spec:
  encryptedData:
    DB_PASSWORD: AgA/7dVsepWtoY2dpj+GhNEVUAUSQkSmOgsDyTf6H9EQuOieMFL6I32XE0epm9CnutMvrQqlTkXa2KIZ01kRzJALnmQGwLUqvAHQCjv8kPKFlJW+ObO2y4PQmdIXo52m46XQT6gPnUS+3bJY2sBXU2hqC7wQ3jD8XJFj0sc0Q9pA2XgYnUTicTapToIP/lhEAm6TjzAwVMbTvzVLIvgtIm3g5oxSy6Z1AB7OWSjkwhfkYYDAy4zGC0KrvCKxgq6h53mrbQYQ1/IGP7ZJOD1ncpIwe2lp5L7Hpukr6VgPAGWmL3DGx6PdqKRjaft7t1iWbE8u6ylGGSf8JicwmQhQQMxE+A08iffycKqTp6F2/fqchko1M0V/7rCnmEqkeDGld/a4G12oeK0JusYttb9WEQKHv+XZbRh+t6+S4fpVaHdZ93dJma6Is/cd19f4SjhS4qHeA468uvD1pKfwt4PU1/U+fFaV8nipaY1acQeHQIP3T9nnNX1Mc+n1fmc9NYdzhayk6D8IRmWyX8RTvQbU3kZYkvmeKttS3GV2Cknr+muSb1TA/9jRsw7G2bxs+urHauo7PWP7ArCImhzIkBktmnySilsZXfllJt03AMZ1/1mQwwG3GL5KSkvYeldHQMYgbCqKsYSL2uAkpBaqT7cILVGKFJYjJwtJSYHc7jZ6QrMlG613uZWy/Pz3TExqJT9eEtEk3Jd4BnPE8j6eTV6tHoPD
    OPENAI_API_KEY: AgCwsDrWS3YWmwHB9lridycRaBoRsDdQ7j+a9elIqSgqWWGZnW63Wk68mQol5fsE2HuXfX2xV+KKFqqUkzwDwL51VkuTXvURYArIkxwKFRxRJALYrESDCzxXo+cPWZc/VLI6fzNd2+lWufJr7Mrtqgo+jddCsEAVvlDZOrUFfHPTF0QW3q9uvMxFQijoOZ7H7f/5C4Wy99koO11cTMQ74RiD0RPALoPhdBkEJ/PPAzTUmzWOH1151LSUPM9P2AP0oR0hVsVVzc/w07CSGKHItZMBJJXMe3EqN31T9UcWtusxxglWNZiC8fdIOz3tu3ZVtqvlXqRXrLIMH1Kcz2y0mPqK10ZSc/+qoQ6XOlj9xXTRT4QRelELzLvRvHAWKaFN7FTBrdqBV8nhXr+6p3j7JLYU8VQ064O9bqteYJKBfljScKeLfotJjLCzAw+qYdcoTtq82iWPCcvsyyZQ/0beJw7C8klm7tJoArjk+viesaOz91Oz7G8GLWep/iCod08bttVEO3eR6F3i6glvDZN4u+42Id/x4JRlVP4MwAYs6mqYJw3OsgUFWVreoXIehiEctF7JBoYZU74mW1AjijNCUsg03US7y74nCtFxK9dZaXTYZIb1jMHHkd88+p8DuERxyyRPrsmvd+cn3AETYHbfoGrqufPIDH3pG1BzlGs3lzh/bnMwqocFVFC43I1fkDuFzptWYhzAq2iuLCgSGOTVdOAUrkA4334QrqYt6SLGWSzWhEFNpVP2IzXJq5XZQXQy2xiEPeggfiPlB/wkWMvvhNSZ0pylb6CZAEpZ3eawRisl3Wl4sVynKUtDZ2J6rbva3ah7jHrxpn/opYy2QNvGvBTGY9FDi2Oa+B77UqwR8+ktmG+1CJi5kvwuIUQsDl2pcS3/ggayJSwiwjodGgRTOyUN3YM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cipher-quest-be
      namespace: welld-staging
